name: on-push-workflow
on: [push, pull_request]

jobs:
  lint-test-build:
    name: lint test and build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # Supporting node versions mentioned here:
        # https://nodejs.org/en/about/releases/
        node-version: [14.x, 12.x, 10.x]

    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: setup node v${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: install deps
        run: npm ci

      - name: lint
        run: npm run lint

      - name: test
        run: npm run test

      - name: build
        run: npm run build
  # attempted fix with:
  # https://stackoverflow.com/questions/58475748/github-actions-how-to-check-if-current-push-has-new-tag-is-new-release
  publish:
    name: publish
    runs-on: ubuntu-latest
    needs: lint-test-build
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: setup node v14
        uses: actions/setup-node@v1
        with:
          node-version: 14
          # Specifies the registry, this field is required!
          registry-url: https://registry.npmjs.org/
      - name: publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
