name: on-release-workflow
on:
  # run on push of tag
  push:
    tags:
      - '*.*'

jobs:
  publish-to-npm:
    name: publish to npm
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # Supporting node versions mentioned here:
        # https://nodejs.org/en/about/releases/
        node-version: [14.x, 12.x, 10.x]

    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: setup node v${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          # Specifies the registry, this field is required!
          registry-url: https://registry.npmjs.org/

      - name: install deps
        run: npm ci

      - name: lint
        run: npm run lint

      - name: test
        run: npm run test

      - name: build
        run: npm run build

      - name: publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
