name: on-release-workflow
on:
  # run on push of tag
  push:
    tags:
      - '*.*'

jobs:
  publish-to-npm:
    name: publish to npm
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: setup node v14, for npm
        uses: actions/setup-node@v1
        with:
          node-version: '14'
          registry-url: https://registry.npmjs.org/

      - name: install deps
        run: npm ci

      - name: lint
        run: npm run lint

      - name: test
        run: npm run test

      - name: build
        run: npm run build

      # publish to npm
      - name: publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}

      # I couldn't get this to work :/
      # - name: setup node v14, for github
      #   uses: actions/setup-node@v1
      #   with:
      #     node-version: '14'
      #     registry-url: 'https://npm.pkg.github.com'
      #     scope: '@bradtaniguchi'

      # # publish to github packages
      # - name: publish to github
      #   run: npm publish
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
